# Generated by Django 3.1.6 on 2021-09-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0002_auto_20210904_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='style',
            field=models.IntegerField(choices=[(0, 'Salsa On1'), (1, 'Bachata'), (2, 'Salsa Calena'), (3, 'Salsa Fusion')]),
        ),
    ]
