# Generated by Django 3.1.6 on 2021-07-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0002_auto_20210727_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
