# Generated by Django 3.1.6 on 2021-09-04 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0003_auto_20210904_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danceapp.style'),
        ),
    ]
