# Generated by Django 3.1.6 on 2021-07-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0006_style_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='danceapp.Tag'),
        ),
    ]
