# Generated by Django 3.1.6 on 2021-07-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0009_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.URLField(max_length=600),
        ),
    ]
