# Generated by Django 3.1.6 on 2021-07-28 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0011_auto_20210728_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
    ]
