# Generated by Django 3.1.6 on 2021-07-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0012_auto_20210728_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(default='test', max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
