# Generated by Django 3.1.6 on 2021-08-04 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0014_remove_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='class_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
