# Generated by Django 3.1.6 on 2021-08-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0015_video_class_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
    ]
