# Generated by Django 3.1.6 on 2021-08-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='level',
            field=models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
