# Generated by Django 3.1.6 on 2021-08-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0022_video_saved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
