# Generated by Django 3.1.6 on 2021-08-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0025_video_calena_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='calena_steps',
            field=models.ManyToManyField(blank=True, related_name='videos', to='danceapp.CalenaStep'),
        ),
        migrations.AlterField(
            model_name='video',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='favourites', to='danceapp.Student'),
        ),
    ]
