# Generated by Django 3.1.6 on 2021-08-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0026_auto_20210825_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_notifications',
            field=models.IntegerField(default=0),
        ),
    ]
