# Generated by Django 3.1.6 on 2021-08-31 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0027_user_unread_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
